/* START PAGE - ALL SUBPAGES */
const START_PAGE_LOGO_HEADER = 'Photo to Letters';
const START_PAGE_LOGO_SUB_HEADER = 'makes life simple';
const START_PAGE_CREATE_ACCOUNT_BUTTON_TEXT = 'Create account';
const START_PAGE_LOGIN_TO_ACCOUNT_BUTTON_TEXT = 'Login to Account';

/* START PAGE EASY */
const START_PAGE_EASY_TUTORIAL_HEADER = 'It\'s easy';
const START_PAGE_EASY_TUTORIAL_CONTENT_FIRST_LINE = 'Just make a photo, or import';
const START_PAGE_EASY_TUTORIAL_CONTENT_SECOND_LINE = 'images to get pure text and';
const START_PAGE_EASY_TUTORIAL_CONTENT_THIRD_LINE = 'save it as document!';

/* START PAGE STARTED */
const START_PAGE_STARTED_TUTORIAL_HEADER = 'Let\'s get started';
const START_PAGE_STARTED_TUTORIAL_CONTENT_FIRST_LINE = 'Why you should write';
const START_PAGE_STARTED_TUTORIAL_CONTENT_SECOND_LINE = 'every letter manually?';
const START_PAGE_STARTED_TUTORIAL_CONTENT_THIRD_LINE = 'Photo2Letters will do it for you!';

/* START PAGE FAST */
const START_PAGE_FAST_TUTORIAL_HEADER = 'It\'s fast';
const START_PAGE_FAST_TUTORIAL_CONTENT_FIRST_LINE = 'It will take only 10 seconds';
const START_PAGE_FAST_TUTORIAL_CONTENT_SECOND_LINE = 'to import the image,';
const START_PAGE_FAST_TUTORIAL_CONTENT_THIRD_LINE = 'and create the text document.';

/* LOGIN PAGE */
const LOGIN_PAGE_HEADER = 'Login';
const LOGIN_PAGE_SUB_HEADER = 'Make sure that data is valid';
const LOGIN_PAGE_FORGOT_PASSWORD = 'Forgot password?';

/* REGISTER PAGE */
const REGISTER_PAGE_HEADER = 'Register your profile';
const REGISTER_PAGE_SUB_HEADER = 'It\'s the last step';

/* GLOBAL */
const EMAIL_INPUT_PLACEHOLDER = 'email';
const PASSWORD_INPUT_PLACEHOLDER = 'password';
const RE_TYPE_PASSWORD_INPUT_PLACEHOLDER = 're-type password';

export {
    START_PAGE_LOGO_HEADER,
    START_PAGE_LOGO_SUB_HEADER,
    START_PAGE_CREATE_ACCOUNT_BUTTON_TEXT,
    START_PAGE_LOGIN_TO_ACCOUNT_BUTTON_TEXT,
    START_PAGE_EASY_TUTORIAL_HEADER,
    START_PAGE_EASY_TUTORIAL_CONTENT_FIRST_LINE,
    START_PAGE_EASY_TUTORIAL_CONTENT_SECOND_LINE,
    START_PAGE_EASY_TUTORIAL_CONTENT_THIRD_LINE,
    START_PAGE_STARTED_TUTORIAL_HEADER,
    START_PAGE_STARTED_TUTORIAL_CONTENT_FIRST_LINE,
    START_PAGE_STARTED_TUTORIAL_CONTENT_SECOND_LINE,
    START_PAGE_STARTED_TUTORIAL_CONTENT_THIRD_LINE,
    START_PAGE_FAST_TUTORIAL_HEADER,
    START_PAGE_FAST_TUTORIAL_CONTENT_FIRST_LINE,
    START_PAGE_FAST_TUTORIAL_CONTENT_SECOND_LINE,
    START_PAGE_FAST_TUTORIAL_CONTENT_THIRD_LINE,
    LOGIN_PAGE_HEADER,
    LOGIN_PAGE_SUB_HEADER,
    LOGIN_PAGE_FORGOT_PASSWORD,
    EMAIL_INPUT_PLACEHOLDER,
    PASSWORD_INPUT_PLACEHOLDER,
    RE_TYPE_PASSWORD_INPUT_PLACEHOLDER,
    REGISTER_PAGE_HEADER,
    REGISTER_PAGE_SUB_HEADER
}