/* CONSTANT VARIABLES FOR START PAGE */
const START_PAGE_LOGO_HEADER = 'Photo to Letters';
const START_PAGE_LOGO_SUBHEADER = 'makes life simple';
const START_PAGE_TUTORIAL_HEADR = 'It\'s easy';
const START_PAGE_TUTORIAL_CONTENT_FIRST_LINE = 'Just make a photo, or import';
const START_PAGE_TUTORIAL_CONTENT_SECOND_LINE = 'images to get pure text and';
const START_PAGE_TUTORIAL_CONTENT_THIRD_LINE = 'save it as document!';
const START_PAGE_CREATE_ACCOUNT_BUTTON_TEXT = 'Create account';
const START_PAGE_LOGIN_TO_ACCOUNT_BUTTON_TEXT = 'Login to Account';

export {
    START_PAGE_CREATE_ACCOUNT_BUTTON_TEXT,
    START_PAGE_LOGO_HEADER,
    START_PAGE_LOGO_SUBHEADER,
    START_PAGE_TUTORIAL_HEADR,
    START_PAGE_TUTORIAL_CONTENT_FIRST_LINE,
    START_PAGE_TUTORIAL_CONTENT_SECOND_LINE,
    START_PAGE_TUTORIAL_CONTENT_THIRD_LINE,
    START_PAGE_LOGIN_TO_ACCOUNT_BUTTON_TEXT
}